### ISSUE TITLE
🐛 "Could not create symlink... (File exists)" 

### ISSUE THREAD

**Issue by thundergolfer** [bazelruby/rules_ruby#54]
### Description 

I have a [failing CI build here](https://buildkite.com/thundergolfer-inc/the-one-true-bazel-monorepo/builds/109#2aa578d2-d3be-444e-9550-c524097bdd0f). 

```
File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/2800332926ca5670e559e7706ead37a8/external/bazelruby_ruby_rules/ruby/private/toolchains/ruby_runtime.bzl", line 52, in _install_dirs
--
  | ctx.symlink(path, rel_path)
  | java.io.IOException: Could not create symlink from /usr/include to /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/2800332926ca5670e559e7706ead37a8/external/org_ruby_lang_ruby_toolchain/usr/include: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/2800332926ca5670e559e7706ead37a8/external/org_ruby_lang_ruby_toolchain/usr/include (File exists)
```

This is working locally, but failing in CI. 

----

**`rules_ruby` version:** `a0d21e570f79424e6125df6c691ab27ed7454e1a`
**Bazel version:** 2.0.0

**Comment by thundergolfer** [comment]
This might be a good opportunity to dig through the code and fix my own issue.

**Comment by thundergolfer** [comment]
When I log onto a CI instance and run the tests, things work fine... 🤔

**Comment by kigster** [comment]
It looks like your rules are trying to build new ruby interpreter and then create symlinks to /usr/bin etc, and I bet it’s failing due to permissions problem.

If I’m correct you have two options:

1. Run your Ci as root so these links can be created
2. But I would recommend installing ruby in your CI Docker image and then specifying ruby interpreter as `host` when registering Ruby toolchain.

Host option also does not limit you to the only two versions of ruby 2.6 we currently support for building the interpreter. 

It will also significantly speed up your build time.

Hope this helps!

**Comment by thundergolfer** [comment]
Thanks for the reply. I wouldn't expect to see `(File exists)` if it was a permissions thing? 

Sounds like I really just need to setup up the tooling to build AMIs for CI rather than just using the stock Amazon Linux 2 AMI. 

Cheers

**Comment by kigster** [comment]
Closing since it's unclear if we need to do anything.

**Comment by snnn** [comment]
I still get the same error while building https://github.com/kythe/kythe.git on my local dev machine(Fedora 34). 
Bazel version: 4.2.0
rules_ruby version: 0.4.1
