### ISSUE TITLE
ruby_test and ruby_rspec rules use system ruby

### ISSUE THREAD

**Issue by Gasparila** [bazelruby/rules_ruby#63]
When running on my local Mac (Mojave 10.14), trying to run any `ruby_test` or `ruby_rspec`
rules crashes with the following error:
```
/private/var/tmp/_bazel_kevinmiller/f7932d341642f6d347f4cead95172a70/execroot/__main__/bazel-out/darwin-fastbuild/bin/ruby_utils/test_rspec.runfiles/__main__/ruby_utils/test_rspec:47:in `get_repository_imports': undefined method `children' for Dir:Class (NoMethodError)
	from /private/var/tmp/_bazel_kevinmiller/f7932d341642f6d347f4cead95172a70/execroot/__main__/bazel-out/darwin-fastbuild/bin/ruby_utils/test_rspec.runfiles/__main__/ruby_utils/test_rspec:99:in `main'
	from /private/var/tmp/_bazel_kevinmiller/f7932d341642f6d347f4cead95172a70/execroot/__main__/bazel-out/darwin-fastbuild/bin/ruby_utils/test_rspec.runfiles/__main__/ruby_utils/test_rspec:125:in `<main>'
```

My guess is that the setup is using my system ruby (2.3.5) which doesn't support `Dir.children`

WORKSPACE:
```
...
load(
    "@bazel_tools//tools/build_defs/repo:git.bzl",
    "git_repository",
)

git_repository(
    name = "bazelruby_ruby_rules",
    commit = "fafab7ebb658857e150b80c39155b75b7f67fde2", # Head as of Feb 4, 2020
    remote = "https://github.com/bazelruby/rules_ruby.git",
)

load(
    "@bazelruby_ruby_rules//ruby:deps.bzl",
    "ruby_register_toolchains",
    "ruby_rules_dependencies",
)

ruby_rules_dependencies()

ruby_register_toolchains(version = "2.6.5")

load("@bazelruby_ruby_rules//ruby:defs.bzl", "ruby_bundle")

ruby_bundle(
    name = "bundle",
    gemfile = "//:BazelGemfile",
    gemfile_lock = "//:BazelGemfile.lock",
    bundler_version = "2.0.2",
    visibility = ["//visibility:public"],
)
```

BUILD:
```
load(
    "@bazelruby_ruby_rules//ruby:defs.bzl",
    "ruby_binary",
    "ruby_library",
    "ruby_rspec",
    "ruby_test",
)

filegroup(
    name = "sources",
    srcs = glob([
        "lib/**/*.rb",
    ]),
)

filegroup(
    name = "specs",
    srcs = glob([
        "spec/**/*.rb",
    ]),
)

ruby_library(
    name = "lib",
    srcs = [":sources"],
    includes = ["lib"],
    deps = [
        "@bundle//:sorbet-runtime",
    ],
)

ruby_test(
  name = "test_rspec",
  main = "example_spec.rb",
  srcs = [
    ":specs",
  ],
  deps = [
    ":lib",
  ]
)
```

**Comment by kigster** [comment]
Thanks for logging this.

Do you have 2.6.5 installed locally? Or is it being built by bazel?

**Comment by Gasparila** [comment]
I have 2.6.5 installed via rvm but not directly on the system. It was built by bazel on my first bazel build.

**Comment by kigster** [comment]
I do not believe that bazel installs ruby via rvm. So if you do have rvm installed, could you try to disable it and retest bazel build?

When bazel installs ruby it downloads and compiles the interpreter directly without using rvm or rbenv.

**Comment by rkallal** [comment]
I am playing with ruby_binary generating a tool that is then used by another rule (lets call the other rule foo_rule). I would expect the foo_rule to not require knowing about the the ruby toolchain used by the ruby_binary that generated the "executable". I set toolchain to 2.6.5 and bazel downloaded and compiled ruby (well it passed off the compile to the ruby build flow). So 2.6.5 is in the bazel build tree. 

My foo_rule calls the DefaultInfo.files_to_run.execute provided by ruby_binary. That fails because the ruby version my companies linux compute farm has is old on and it is before Dir.children became a ruby feature. My foo_rule sets use_default_shell_env = False. My theory is that the #!/usr/bin/env eventually finds whatever version was installed on the linxu system when the invoked path is empty. 

This fails:
```
def get_repository_imports(runfiles)
  Dir.children(runfiles).map {|d|
    File.join(runfiles, d)
  }.select {|d|
    File.directory? d
  }
end
```

Looking at the bazel python wrapper template it is a sh script. https://github.com/bazelbuild/bazel/tree/master/tools/python.

**Comment by rkallal** [comment]
There is a comment in the bazel python wrapper .sh template that covers the basic issue that I am seeing. It comments that ctx.actios.run() will unset the path. 

```
# We use `which` to locate the Python interpreter command on PATH. `command -v`
# is another option, but it doesn't check whether the file it finds has the
# executable bit.
#
# A tricky situation happens when this wrapper is invoked as part of running a
# tool, e.g. passing a py_binary target to `ctx.actions.run()`. Bazel will unset
# the PATH variable. Then the shell will see there's no PATH and initialize its
# own, sometimes without exporting it. This causes `which` to fail and this
# script to think there's no Python interpreter installed. To avoid this we
# explicitly pass PATH to each `which` invocation. We can't just export PATH
# because that would modify the environment seen by the final user Python
# program.
#
# See also:
#
#     https://github.com/bazelbuild/continuous-integration/issues/578
#     https://github.com/bazelbuild/bazel/issues/8414
#     https://github.com/bazelbuild/bazel/issues/8415
```

**Comment by rkallal** [comment]
Automatically adding Dir.children solves one of the issues. However, it still leaves the tool that was created by ruby_binary not picking up the ruby toolchain. This is because other tools invoke using ctx.actions.run() and ctx.actions.run() does not (and probably should not) have a reference to the ruby toolchain. What is really strange is that the expansion of the binary_wrapper.tpl passes in a field call _interpreter_ but that appears to never be used in the binary_wrapper.tpl.

How the binary_wrapper.tpl file currently selects its ruby interpreter:
```
def find_ruby_binary
  File.join(
    RbConfig::CONFIG['bindir'],
    RbConfig::CONFIG['ruby_install_name'],
  )
end
```

The template expansion passing in _interpreter_ that is never used.
```
   ctx.actions.expand_template(
        template = ctx.file._wrapper_template,
        output = executable,
        substitutions = {
            "{loadpaths}": repr(deps.incpaths.to_list()),
            "{rubyopt}": repr(rubyopt),
            "{main}": repr(_to_manifest_path(ctx, main)),
            "{interpreter}": _to_manifest_path(ctx, interpreter),
            "{gem_path}": gem_path,
            "{should_gem_pristine}": str(len(gems_to_pristine) > 0).lower(),
            "{gems_to_pristine}": " ".join(gems_to_pristine),
        },
    )
```

**Comment by kigster** [comment]
Thanks! I’ll take a look at why it’s picking the wrong interpreter.

Just so you know, on my system I have the following setup that seems to work:

* using rbenv I installed 2.7.0
* I have in my bashrc the following:

```bash
export PATH=$HOME/.rbenv/shims:$PATH
```

I’d be curious if the above setup fixes your immediate problem.

**Comment by kigster** [comment]
Also. we specifically opted for not disabling shell variables so that the right version of ruby can be found when it’s installed locally via rbenv. Perhaps you can change that flag and retest?

**Comment by kigster** [comment]
## Warning

Please note the name changes on the rules initialization methods merged with the last PR. Follow the README syntax and you should be fine.

**Comment by rkallal** [comment]
# This fails because define_method is private
# Ruby 2.4 and older does not have +.children+
# So we define it.
#unless Dir.respond_to?(:children)
#  Dir.define_method :children do |dir|
#    Dir.entries(dir).reject { |entry| %w(. ..).include?(entry) }
#  end
#end

# This works but it seems expensive since the Dir.children method is used once in the template.
unless Dir.respond_to?(:children)
  Dir.class.send :define_method, :children do |dir|
   Dir.entries(dir).reject { |entry| %w(. ..).include?(entry) }
  end
end

# I did this in my local clone to get around the DIR.children issue:
def get_repository_imports(runfiles)
  children = Dir.entries(runfiles) - [".",".."]
  children.map {|d|
    File.join(runfiles, d)
  }.select {|d|
    File.directory? d
  }
end

**Comment by kigster** [comment]
Submit a PR?

**Comment by rkallal** [comment]
Will shortly submit a PR. 

Onto the rbenv discussion. I installed rbenv to my linux ~ and ruby 2.7.  Yes ruby2.7 whichs as /home/<username>/.rbenv/shims/ruby and with ctx.actions.run(use_default_shell_env = True the correct ruby version is found. However, our tools flow uses work areas like Google and works areas completely override users tooling versions. Defaulting to finding the user version of ruby removes the hermetic protection. I will play around a little more with getting the flow to pick the bazel toolchain version.

**Comment by kigster** [comment]
Yes it’s true that it’s not technically hermetic. Not only that, but any gems installed into the rbenv ruby will be available to the bazel builds unless environment is sterilized.

The reason we opted for not resetting environment is that we currently do not attach a proper C/C++ toolchain for building gems with native extensions. We get native extensions for free on systems where gcc is found on a host system. 

If you create a pristine environment you won’t be able to install gems with native extensions without significant additional effort.

Anyway, any help in this area is much appreciated.

**Comment by lalten** [comment]
@rkallal It would be awesome if you could submit your fixes as PR. I replicated https://github.com/bazelruby/rules_ruby/issues/63#issuecomment-593177541 and it solved my problem in  https://github.com/bazelruby/rules_ruby/issues/74

**Comment by kigster** [comment]
@lalten @rkallal I will try to find time to work on this next week. If anyone wants to remote-pair with me, that'd be dope. Hit me up at kig AT kig.re

**Comment by lalten** [comment]
I'm running into this problem again. I have a test that invokes something that runs a ruby_binary target inside. The test rule invokes the whole thing with ctx.actions.run, which iiuc, always uses system Ruby instead of any installed rules_ruby toolchain.
This is a problem because the system ruby is way too old and we generally don't want to load any system libraries in our hermetic build.
Did you ever find some time to look into this @kigster?
